site_name: Flask-RESTAPI
repo_url: https://github.com/JonarsLi/flask-restapi
repo_name: JonarsLi/flask-restapi
nav:
  - Overview: index.md
  - Install: install.md
  - Quickstart: quickstart.md
  - Decorators:
    - Path: decorators/path.md
    - Query: decorators/query.md
    - Header: decorators/header.md
    - Body: decorators/body.md
    - Form: decorators/form.md
    - Auth: decorators/auth.md
    - Response: decorators/response.md
  - Security:
    - JWT: security/jwt.md
  - OpenAPI: openapi.md
  - Blueprint: blueprint.md
  - Function Based View: function_based_view.md
theme:
  name: "material"
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.details
  - admonition
  - def_list
  - toc:
      permalink: true