site_name: Flask-RESTAPI
repo_url: https://github.com/JonarsLi/flask-restapi
repo_name: JonarsLi/flask-restapi
nav:
  - Overview: index.md
  - Install: install.md
  - Quickstart: quickstart.md
  - Decorators:
    - Path: decorators/path.md
    - Query: decorators/query.md
    - Header: decorators/header.md
    - Body: decorators/body.md
    - Form: decorators/form.md
    - Auth: decorators/auth.md
    - Response: decorators/response.md
    - Blueprint Map: decorators/bp_map.md
  - Response: response.md
  - Tag: tag.md
  - Upload files: files.md
  - OpenAPI: openapi.md
  - Function Based View: function_based_view.md
  - API Reference:
    - Core: api/core.md
    - Exceptions: api/exceptions.md
theme:
  name: "material"
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: true
            show_source: true
      watch:
        - flask_restapi

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.details
  - admonition
  - def_list
  - toc:
      permalink: true