site_name: Flask-RESTAPI
repo_url: https://github.com/JonarsLi/flask-restapi
repo_name: JonarsLi/flask-restapi
nav:
  - Overview: index.md
  - Install: install.md
  - Quickstart: quickstart.md
  - OpenAPI: openapi.md
  - Decorators: decorators.md
  - Blueprint: blueprint.md
  - Function based view: function_based_view.md
theme:
  name: "material"
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.details
  - admonition
  - def_list